backendReplicaCount: 2
image:
  repository: abinetdegefa/voteapp-backend
  tag: v2
  pullPolicy: IfNotPresent
global:
  env: staging
service:
  type: ClusterIP
  port: 8000
namespace:
  name: ns-test
db:
  name: votedb
  host: example.com
  user: postgres
  password: ""
statefulSet:
  name: db
dbReplicaCount: 1
postgresImage:
  repository: postgres:15
volume:
  mountPath: "/var/lib/postgresql/data"
frontendReplicaCount: 1
frontendImage:
  name: abinetdegefa/voteapp-frontend:v2
ingressClass:
  name: nginx
  host: example.com
backendPath: /api
frontendPath: /
frontendService:
  port: 80
persistentVolume:
  capacity: 1Gi
  accessMode: ReadWriteOnce
  storageClassName: standard
  hostpath:
    path: "/mnt/data/postgres"
SECRET_KEY: django-insecure-_5x9q8q-j5g1l(!49r=9uu=b=yf7m0md1ze2x&intpqhy-tg2@
